### Fetch User Data with Authorization
GET https://taskvalidator-backend.onrender.com/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaXJhbSIsImlhdCI6MTczNTU2NTYwMSwiZXhwIjoxNzM1NTY5MjAxfQ.dML1zX4s4rhg59BF1_IJsGJYSKYGY23Jcqo6zEq1gHk


### Login Request
POST https://taskvalidator-backend.onrender.com/login
Content-Type: application/json

{
  "username": "sairam",
  "password": "SaiNaga143@"
}

###
GET https://taskvalidator-backend.onrender.com/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaXJhbSIsImlhdCI6MTczNTU2NTYwMSwiZXhwIjoxNzM1NTY5MjAxfQ.dML1zX4s4rhg59BF1_IJsGJYSKYGY23Jcqo6zEq1gHk
